[package]
name = "rson_derive"
version = "0.1.0"
authors = ["dragfire <asem.devajit@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.21"
quote = "1.0.7"
syn = "1.0.41"
